pipeline {
    agent any 
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f AirTNT/pom.xml clean package'
            }
            post {
                success {
                    echo 'Now Archiving the artifacts.....'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        Stage('Create Tomcat Docker Image') {
            steps {
                sh 'docker build . -t tomcatsamplewebapp:${env.BUILD_ID}'
            }
        }
    }
}