pipeline {
    agent any 
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f AirTNT/pom.xml clean package'
            }
            post {
                success {
                    echo 'Now Archiving the artifacts.....'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create Tomcat Docker Image') {
            steps {
                sh "sudo docker build ./AirTNT/Dockerfile -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }
    }
}