job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}")
    scm {
        git("https://github.com/skqist225/AirTNT2.git", "main")
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'AirTNT/pom.xml')
    }
    publishers {
        archiveArtifacts '**/*.war'
    }
}